###########################################
### Deployment
###########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: test-app
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-app
    spec:                     
      containers:
        # Nginx
        - image: npohosting/nginx:1.17
          imagePullPolicy: Always
          name: nginx
          command:
            - /usr/libexec/s2i/run
          ports:
            - containerPort: 9000
              protocol: TCP
          resources: {}                       
      restartPolicy: Always
      securityContext: {}          
